vim.keymap.set("n", "<F1>", "<cmd>lua TermfloatToggle()<CR>")
vim.keymap.set("n", "<F2>", "<cmd> lua require('dapui').toggle() <CR>")
vim.keymap.set("n", "<F3>", "<cmd> lua require'dap'.repl.toggle()<cr>")
vim.keymap.set("n", "<F5>", "<cmd> lua require'dap'.continue() <CR>")
vim.keymap.set("n", "<F6>", "<cmd> lua require'dap'.terminate() <CR>")
vim.keymap.set("n", "<F9>", "<cmd> DapToggleBreakpoint <CR>")
vim.keymap.set("n", "<F10>", "<cmd> lua require'dap'.step_over() <CR>")
vim.keymap.set("n", "<F11>", "<cmd> luarequire'dap'.step_into() <CR>")
vim.keymap.set("n", "<F12>", "<cmd> lua require'dap'.step_out() <CR>")
